[build]
  command = "npm run build"
  publish = "build"

# Handle SPA routing - redirect all routes to index.html except for static assets
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Ensure manifest.json is served as JSON
[[headers]]
  for = "/manifest.json"
  [headers.values]
    Content-Type = "application/json"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
